version: "3.9"

services:
  user-service:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=users_db
      - JWT_SECRET=supersecret
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules inside container

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

volumes:
  user_db_data:

