services:
  order-service:
    build: .
    ports:
      - "4002:4002"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=orders_db
      - USER_SERVICE_URL=http://host.docker.internal:4000
      - PRODUCT_SERVICE_URL=http://host.docker.internal:4001
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
