services:
  order-service:
    build: .
    ports:
      - "4002:4002"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=orders_db
      - JWT_SECRET=supersecret
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
